#include<stdio.h>
int main()
{
    // THE ARITHMETIC OPERATION WE DO IN MATHEMATICS, WE NEED TO PERFORM SIMILAR OPERATION IN OUR PROGRAMS TO SOLVE QUESTIONS.
    // TO PERFORM MATHEMATICAL OPERATION WE USE ARITHMATIC OPERATIONS
    
    double num1,num2,num3;

    printf("")










    return 0;
}